extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  comments:
    min-spaces-from-content: 1

  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  indentation:
    spaces: 2
    indent-sequences: consistent
